In [1]:
import numpy as np
import pandas as pd

In [2]:
import pandas as pd

df = pd.read_csv('D:\Cluster\Assesment\supplier_sales.csv')

print(df.head())

         id  supplier_id  invoice_id  prod_id        product_name  quantity  \
0  48652728           59       32259        7  سيبروسين مرهم س--ج        10
1  48652935           59       32281        7  سيبروسين مرهم س--ج         3
2  48653089           59       32301        7  سيبروسين مرهم س--ج         2
3  48653301           59       32334        7  سيبروسين مرهم س--ج         5
4  49140754           59      100804        7  سيبروسين مرهم س--ج        10

   discount  total_amount  account_id                      account_name  \
0      15.0        178.50         637  ص مها مديرية امن الجيزة &ش*& 003
1      15.0         53.55        4365                ص السعدنى فيصل 002
2      21.0         33.18        3297        ص منى احمد امبابه نقدى 004
3      20.0         84.00        5734                س الشفاء بشتيل 004
4      17.0        174.30         637  ص مها مديرية امن الجيزة &ش*& 003

                                account_address  user_id   user_name  \
0                 كوبرى الجلاء ميدان فينى الدقى        6  نهى الدالى
1      شارع مصرف جلال خلف فندق قاعود بجوار مسجد        6  نهى الدالى
2  شارع جمال عبد الناصر امام مدرسه تبارك الخاصه      137   اسماء رجب
3                        ش الحريه بجوار المدرسه      137   اسماء رجب
4                 كوبرى الجلاء ميدان فينى الدقى        6  نهى الدالى

  employee_name  city  region  area  area_id        creation_date  \
0    نهى الدالى   NaN     NaN   NaN      NaN  2025-05-25 13:43:10
1    نهى الدالى   NaN     NaN   NaN      NaN  2025-05-25 14:35:04
2     اسماء رجب   NaN     NaN   NaN      NaN  2025-05-25 15:21:21
3     اسماء رجب   NaN     NaN   NaN      NaN  2025-05-25 20:49:54
4    نهى الدالى   NaN     NaN   NaN      NaN  2026-04-12 13:51:32

            created_at
0  2026-05-19 16:29:03
1  2026-05-19 16:29:03
2  2026-05-19 16:29:03
3  2026-05-19 16:29:03
4  2026-05-19 16:47:49

<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Ahmed\AppData\Local\Temp\ipykernel_17460\2791127716.py:3: SyntaxWarning: invalid escape sequence '\C'
  df = pd.read_csv('D:\Cluster\Assesment\supplier_sales.csv')

In [3]:
df.isna().sum()

id                     0
supplier_id            0
invoice_id             0
prod_id                0
product_name           0
quantity               0
discount               0
total_amount           0
account_id             0
account_name           0
account_address     2560
user_id                0
user_name            512
employee_name       3279
city               10000
region             10000
area               10000
area_id            10000
creation_date          0
created_at             0
dtype: int64

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               10000 non-null  int64
 1   supplier_id      10000 non-null  int64
 2   invoice_id       10000 non-null  int64
 3   prod_id          10000 non-null  int64
 4   product_name     10000 non-null  str
 5   quantity         10000 non-null  int64
 6   discount         10000 non-null  float64
 7   total_amount     10000 non-null  float64
 8   account_id       10000 non-null  int64
 9   account_name     10000 non-null  str
 10  account_address  7440 non-null   str
 11  user_id          10000 non-null  int64
 12  user_name        9488 non-null   str
 13  employee_name    6721 non-null   str
 14  city             0 non-null      float64
 15  region           0 non-null      float64
 16  area             0 non-null      float64
 17  area_id          0 non-null      float64
 18  creation_date    10000 non-null  str
 19  created_at       10000 non-null  str
dtypes: float64(6), int64(7), str(7)
memory usage: 3.3 MB

In [5]:
df.head()

,id,supplier_id,invoice_id,prod_id,product_name,quantity,discount,total_amount,account_id,account_name,account_address,user_id,user_name,employee_name,city,region,area,area_id,creation_date,created_at
0,48652728,59,32259,7,سيبروسين مرهم س--ج,10,15.0,178.50,637,ص مها مديرية امن الجيزة &ش*& 003,كوبرى الجلاء ميدان فينى الدقى,6,نهى الدالى,نهى الدالى,NaN,NaN,NaN,NaN,2025-05-25 13:43:10,2026-05-19 16:29:03
1,48652935,59,32281,7,سيبروسين مرهم س--ج,3,15.0,53.55,4365,ص السعدنى فيصل 002,شارع مصرف جلال خلف فندق قاعود بجوار مسجد,6,نهى الدالى,نهى الدالى,NaN,NaN,NaN,NaN,2025-05-25 14:35:04,2026-05-19 16:29:03
2,48653089,59,32301,7,سيبروسين مرهم س--ج,2,21.0,33.18,3297,ص منى احمد امبابه نقدى 004,شارع جمال عبد الناصر امام مدرسه تبارك الخاصه,137,اسماء رجب,اسماء رجب,NaN,NaN,NaN,NaN,2025-05-25 15:21:21,2026-05-19 16:29:03
3,48653301,59,32334,7,سيبروسين مرهم س--ج,5,20.0,84.00,5734,س الشفاء بشتيل 004,ش الحريه بجوار المدرسه,137,اسماء رجب,اسماء رجب,NaN,NaN,NaN,NaN,2025-05-25 20:49:54,2026-05-19 16:29:03
4,49140754,59,100804,7,سيبروسين مرهم س--ج,10,17.0,174.30,637,ص مها مديرية امن الجيزة &ش*& 003,كوبرى الجلاء ميدان فينى الدقى,6,نهى الدالى,نهى الدالى,NaN,NaN,NaN,NaN,2026-04-12 13:51:32,2026-05-19 16:47:49

In [6]:
import pandas as pd
import re

# 1. Normalize Arabic characters (strip Hamzas and change Ta Marbuta)
arabic_mapping = str.maketrans('أإآةى', 'اااهي')
df['account_name'] = df['account_name'].str.translate(arabic_mapping)

# 2. Safe cleaning (remove strange characters and brackets)
safe_noise_pattern = '[^a-zA-Z0-9\\s\u0600-\u06FF]'
df['account_name'] = df['account_name'].str.replace(safe_noise_pattern, ' ', regex=True)

# 3. Remove single English letters (e.g., dangling 'D' or 'C')
df['account_name'] = df['account_name'].str.replace(r'\b[a-zA-Z]\b', ' ', regex=True)

# 4. Convert single 'ص' (Sad) or 'س' (Seen) at the beginning of the text to 'صيدليه' (Pharmacy)
df['account_name'] = df['account_name'].str.replace(r'^[صس]\s+', 'صيدليه ', regex=True)

# 5. Convert single 'ش' (Sheen) to 'شارع' (Street)
df['account_name'] = df['account_name'].str.replace(r'\bش\s+', 'شارع ', regex=True)

# 6. Merge extra spaces and trim edges (must be the final polishing step)
df['account_name'] = df['account_name'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [7]:
df['account_name'].head()

0    صيدليه مها مديريه امن الجيزه ش 003
1               صيدليه السعدني فيصل 002
2       صيدليه مني احمد امبابه نقدي 004
3               صيدليه الشفاء بشتيل 004
4    صيدليه مها مديريه امن الجيزه ش 003
Name: account_name, dtype: str

In [8]:
# 1. Character Unification
arabic_mapping = str.maketrans('أإآةى', 'اااهي')
df['account_address'] = df['account_address'].str.translate(arabic_mapping)

# 2. Safe Noise Removal (Keeping digits)
# Numbers (0-9) are included here so they won't be deleted, and we removed the 'r' for PyArrow compatibility
safe_noise_pattern = '[^a-zA-Z0-9\\s\u0600-\u06FF]'
df['account_address'] = df['account_address'].str.replace(safe_noise_pattern, ' ', regex=True)

# 3. Replace "ش" with "شارع" (Street)
# This code looks for the letter "ش" on its own (whether at the beginning or preceded by a space) and converts it to "شارع"
# This method ensures that the letter 'ش' inside any word (like "Shubra" or "Shams") remains unaffected
df['account_address'] = df['account_address'].str.replace(r'(^|\s)ش(?=\s|$)', r'\1شارع', regex=True)

# 4. Final Cleanup (Removing extra spaces)
df['account_address'] = df['account_address'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [9]:
df.head()

,id,supplier_id,invoice_id,prod_id,product_name,quantity,discount,total_amount,account_id,account_name,account_address,user_id,user_name,employee_name,city,region,area,area_id,creation_date,created_at
0,48652728,59,32259,7,سيبروسين مرهم س--ج,10,15.0,178.50,637,صيدليه مها مديريه امن الجيزه ش 003,كوبري الجلاء ميدان فيني الدقي,6,نهى الدالى,نهى الدالى,NaN,NaN,NaN,NaN,2025-05-25 13:43:10,2026-05-19 16:29:03
1,48652935,59,32281,7,سيبروسين مرهم س--ج,3,15.0,53.55,4365,صيدليه السعدني فيصل 002,شارع مصرف جلال خلف فندق قاعود بجوار مسجد,6,نهى الدالى,نهى الدالى,NaN,NaN,NaN,NaN,2025-05-25 14:35:04,2026-05-19 16:29:03
2,48653089,59,32301,7,سيبروسين مرهم س--ج,2,21.0,33.18,3297,صيدليه مني احمد امبابه نقدي 004,شارع جمال عبد الناصر امام مدرسه تبارك الخاصه,137,اسماء رجب,اسماء رجب,NaN,NaN,NaN,NaN,2025-05-25 15:21:21,2026-05-19 16:29:03
3,48653301,59,32334,7,سيبروسين مرهم س--ج,5,20.0,84.00,5734,صيدليه الشفاء بشتيل 004,شارع الحريه بجوار المدرسه,137,اسماء رجب,اسماء رجب,NaN,NaN,NaN,NaN,2025-05-25 20:49:54,2026-05-19 16:29:03
4,49140754,59,100804,7,سيبروسين مرهم س--ج,10,17.0,174.30,637,صيدليه مها مديريه امن الجيزه ش 003,كوبري الجلاء ميدان فيني الدقي,6,نهى الدالى,نهى الدالى,NaN,NaN,NaN,NaN,2026-04-12 13:51:32,2026-05-19 16:47:49

In [10]:
import pandas as pd

# 1. Calculate the number of unique names before unification (stored in a variable for plotting)
unique_before = df['account_name'].nunique()

df['account_name'] = df.groupby(['supplier_id', 'account_id'])['account_name'].transform('first')

# 3. Calculate the number of unique names after unification
unique_after = df['account_name'].nunique()

# 4. Print numbers for a quick review
print(f"Number of unique names BEFORE: {unique_before}")
print(f"Number of unique names AFTER: {unique_after}")
print(f"Duplicates Removed: {unique_before - unique_after}")

Number of unique names BEFORE: 1102
Number of unique names AFTER: 1102
Duplicates Removed: 0

In [11]:
import pandas as pd

# 1. Calculate the number of unique addresses before unification
address_unique_before = df['account_address'].nunique()

# 2. Unify the address based on both supplier and account (correct modification)
df['account_address'] = df.groupby(['supplier_id', 'account_id'])['account_address'].transform('first')

# 3. Calculate the number of unique addresses after unification
address_unique_after = df['account_address'].nunique()

# 4. Print numbers for review
print(f"Number of unique addresses BEFORE: {address_unique_before}")
print(f"Number of unique addresses AFTER: {address_unique_after}")
print(f"Duplicate Addresses Removed: {address_unique_before - address_unique_after}")

Number of unique addresses BEFORE: 1024
Number of unique addresses AFTER: 1024
Duplicate Addresses Removed: 0

In [12]:
# import pandas as pd

# # 1. استخراج الأرقام من آخر الاسم في عمود جديد
# # الـ Regex ده بيبحث عن أي أرقام (\d+) في نهاية النص ($)
# df['account_code'] = df['account_name'].str.extract(r'(\d+)$')

# # 2. نشوف هل الأرقام دي مرتبطة بمندوب معين (خط سير)؟
# # الكود ده هيجيبلك أكتر المناديب اللي شغالين على الكود 070 مثلاً
# print(df[df['account_code'] == '070']['employee_name'].value_counts())

# # 3. نشوف هل هي أرقام فروع لعميل واحد؟
# # الكود ده بيجيبلك العملاء اللي ليهم أكتر من كود مختلف
# base_names = df['account_name'].str.replace(r'\s*\d+$', '', regex=True)
# print(df.groupby(base_names)['account_code'].nunique().sort_values(ascending=False).head())

In [12]:
import pandas as pd
from collections import Counter

# 1. Function to extract potential areas from name and address
def extract_potential_areas(row):
    potential_areas = []
    
    name = str(row['account_name'])
    address = str(row['account_address'])
    
    # A. Extract the last word from the address (often the area)
    if address != 'nan' and address.strip():
        words = address.split()
        if len(words) > 1:
            potential_areas.append(words[-1]) # Last word
            potential_areas.append(words[-2] + " " + words[-1]) # Last two words (e.g., "Dar El-Salam")
            
    # B. Extract the word after the owner's name in account_name
    # Assuming the name is often 3 words, the 4th or 5th word is the area
    if name != 'nan' and name.strip():
        words = name.split()
        # Ignore initial words (Pharmacy, Doctor's name) and numbers at the end
        filtered_words = [w for w in words if not w.isdigit() and w not in ['صيدليه', 'شارع', 'س']]
        if len(filtered_words) >= 3:
             potential_areas.append(filtered_words[-1])

    return potential_areas

# 2. Apply the function and aggregate all potential words
all_potential_areas = []
for index, row in df.iterrows():
    all_potential_areas.extend(extract_potential_areas(row))

# 3. Count words to see the most frequent ones (these are likely the actual areas)
area_counts = Counter(all_potential_areas)

# 4. Convert result to a DataFrame for organized display
areas_df = pd.DataFrame(area_counts.items(), columns=['Word', 'Frequency']).sort_values(by='Frequency', ascending=False)

# Display the top 30 most frequent words
print(areas_df.head(30))

               Word  Frequency
566         المنشيه       1020
567    طريق المنشيه        984
568               م        984
578              خط        845
16             فيصل        818
162               ن        388
1556          فيصل1        349
887        المستشفي        326
1592  شارع المستشفي        318
116           سبلاي        272
10           اللواء        241
7              نقدي        229
1560           الجي        220
11       ارض اللواء        205
28            الهرم        203
0             الدقي        203
1553        امبابه3        175
658           فيصل2        156
282          كرداسه        155
26            بشتيل        138
582             ز11        133
53           اكتوبر        129
1559        التصريف        128
524            عقبه        128
31        المهندسين        126
114          الجيزه        123
352       المعتمديه        123
679    الثوره الدقي        118
154            ترسا        115
238          الخيام        113

In [14]:
import pandas as pd
import numpy as np
import re

area_mapping = {
    'المنشيه': 'المنشية', 'فيصل': 'فيصل', 'فيصل1': 'فيصل', 'فيصل2': 'فيصل',
    'امبابه': 'إمبابة', 'امبابه3': 'إمبابة', 'ارض اللواء': 'أرض اللواء',
    'الدقي': 'الدقي', 'الثوره الدقي': 'الدقي', 'الهرم': 'الهرم',
    'كرداسه': 'كرداسة', 'بشتيل': 'بشتيل', 'المهندسين': 'المهندسين',
    'المعتمديه': 'المعتمدية', 'الجيزه': 'الجيزة', 'ترسا': 'ترسا',
    'عقبه': 'ميت عقبة', 'ميت عقبه': 'ميت عقبة', 'الوراق': 'الوراق',
    'حدائق الاهرام': 'حدائق الأهرام', 'ح الاهرام': 'حدائق الأهرام',
    'حدايق الاهرام': 'حدائق الأهرام', 'بولاق الدكرور': 'بولاق الدكرور',
    'البراجيل': 'البراجيل', 'كفر حكيم': 'كفر حكيم', 'برك الخيام': 'برك الخيام',
    'كفر الجبل': 'كفر الجبل', 'البدرشين': 'البدرشين', 'الحوامديه': 'الحوامدية',
    'شبرا مصر': 'شبرا', 'شبرا013': 'شبرا', 'شبرا': 'شبرا', 'بهتيم': 'بهتيم',
    'حلوان': 'حلوان', 'الزمالك': 'الزمالك', 'اكتوبر': 'أكتوبر', 'حدائق اكتوبر': 'حدائق أكتوبر',
    'العمرانيه': 'العمرانية', 'المنيب': 'المنيب', 'كعبيش': 'كعبيش', 'الكوم الاخضر': 'الكوم الأخضر',
    'بهرمس': 'بهرمس', 'المناشي': 'المناشي', 'برطس': 'برطس', 'الكونيسه': 'الكنيسة',
    'منيل الروضه': 'منيل الروضة', 'م نصر': 'مدينة نصر', 'مدينة نصر': 'مدينة نصر',
    'ميت عقيه': 'ميت عقبة', 'ناهيا': 'ناهيا', 'البساتين': 'البساتين', 'وسط البلد': 'وسط البلد',
    'باب الخلق': 'باب الخلق', 'العروبه': 'العروبة', 'صفط': 'صفط اللبن',
    'العجوزه': 'العجوزة', 'الزبتون': 'الزيتون', 'الزيتون': 'الزيتون',
    'الشيخ زايد': 'الشيخ زايد', 'زايد': 'الشيخ زايد', 'الثلاثيني': 'الثلاثيني',
    'ابو النمرس': 'أبو النمرس', 'المنوات': 'المنوات', 'كفر طهرمس': 'كفر طهرمس',
    'برقاش': 'برقاش', 'القراطيين': 'القراطيين', 'مصر الجديده': 'مصر الجديدة',
    'الحدايق': 'الحدائق', 'الملكه': 'الملكة', 'العشرين': 'العشرين',
    'كرادسه': 'كرداسة', 'كعابيش': 'كعبيش', 'السيده زينب': 'السيدة زينب',
    'السيده': 'السيدة زينب', 'المقطم': 'المقطم', 'بولاق': 'بولاق', 'اوسيم': 'أوسيم',
    'الطوابق': 'الطوابق', 'اللبيني': 'اللبيني', 'ابو الهول': 'أبو الهول',
    'ميدان الساعه': 'ميدان الساعة', 'طموه': 'طموه', 'الاخصاص': 'الإخصاص',
    'نكلا': 'نكلا', 'المنصوريه': 'المنصورية', 'نزله الاشطر': 'نزلة الأشطر',
    'المنيل': 'المنيل', 'الرحاب': 'الرحاب', 'كوتسيكا': 'كوتسيكا',
    'المنصوره': 'المنصورة', 'ابو الريش': 'أبو الريش', 'البحر الاعظم': 'البحر الأعظم',
    'ذات الكوم': 'ذات الكوم', 'المعادي': 'المعادي', 'الشرابيه': 'الشرابية',
    'الخصوص': 'الخصوص', 'كفر حجازي': 'كفر حجازي', 'بين السرايات': 'بين السرايات',
    'الضاهر': 'الضاهر', 'غمره': 'غمرة', 'زنين': 'زنين', 'الطالبيه': 'الطالبية',
    'جاردين سيتي': 'جاردن سيتي', 'عمرانيه': 'العمرانية', 'بين السريات': 'بين السرايات',
    'غطاطي': 'غطاطي', 'الجلاتمه': 'الجلاتمة', 'منشاه رضوان': 'منشأة رضوان',
    'ابو رواش': 'أبو رواش', 'سهل حمزه': 'سهل حمزة', 'طناش': 'طناش',
    'المريوطيه': 'المريوطية', 'الخيمه': 'شبرا الخيمة', 'دار السلام': 'دار السلام',
    'بني مجدول': 'بني مجدول', 'القطاميه': 'القطامية', 'القطامية': 'القطامية',
    'مدينه نصر': 'مدينة نصر', 'المساحه': 'المساحة', 'القراطين': 'القراطيين',
    'حدائق': 'الحدائق', 'الكفر': 'الكفر'
}

cairo_areas = ['الزمالك', 'شبرا', 'حلوان', 'مدينة نصر', 'منيل الروضة', 'البساتين', 'وسط البلد', 
               'باب الخلق', 'العروبة', 'الزيتون', 'مصر الجديدة', 'الحدائق', 'السيدة زينب', 
               'المقطم', 'بولاق', 'المنيل', 'الرحاب', 'كوتسيكا', 'أبو الريش', 'المعادي', 
               'الشرابية', 'الضاهر', 'غمرة', 'جاردن سيتي', 'دار السلام', 'القطامية']
qalyubia_areas = ['بهتيم', 'الخصوص', 'شبرا الخيمة']
alex_areas = ['ميدان الساعة']
dakahlia_areas = ['المنصورة']

sorted_dirty_words = sorted(area_mapping.keys(), key=len, reverse=True)

def assign_clean_area_regex(row):
    text_to_search = str(row['account_address']) + " " + str(row['account_name'])
    
    for dirty_word in sorted_dirty_words:
        
        pattern = rf'(?:\s|^){re.escape(dirty_word)}(?:\s|$)'
        if re.search(pattern, text_to_search):
            return area_mapping[dirty_word] 
            
    return np.nan 

df['area'] = df.apply(assign_clean_area_regex, axis=1)

df['city'] = None
df.loc[df['area'].isin(cairo_areas), 'city'] = 'القاهرة'
df.loc[df['area'].isin(qalyubia_areas), 'city'] = 'القليوبية'
df.loc[df['area'].isin(alex_areas), 'city'] = 'الإسكندرية'
df.loc[df['area'].isin(dakahlia_areas), 'city'] = 'الدقهلية'
df.loc[(df['area'].notna()) & (df['city'].isna()), 'city'] = 'الجيزة'

region_mapping = {
    'القاهرة': 'القاهرة الكبرى',
    'الجيزة': 'القاهرة الكبرى',
    'القليوبية': 'القاهرة الكبرى',
    'الإسكندرية': 'الإسكندرية',
    'الدقهلية': 'الدلتا'
}
df['region'] = df['city'].map(region_mapping)


print("--- توزيع المحافظات (City) ---")
print(df['city'].value_counts())

print("\n--- توزيع الأقاليم (Region) ---")
print(df['region'].value_counts())

--- توزيع المحافظات (City) ---
city
الجيزة        6152
القاهرة        700
القليوبية      123
الإسكندرية      27
الدقهلية         2
Name: count, dtype: int64

--- توزيع الأقاليم (Region) ---
region
القاهرة الكبرى    6975
الإسكندرية          27
الدلتا               2
Name: count, dtype: int64

In [15]:
import pandas as pd

# 1. Filter data where the 'area' is still Null
missing_areas_df = df[df['area'].isna()]

# 2. Take a random sample of 20 rows (without duplicates to see more variety)
sample_missing = missing_areas_df[['account_name', 'account_address']].drop_duplicates().sample(n=20, random_state=42)

# 3. Adjust Pandas settings so long addresses are displayed fully without truncation
pd.set_option('display.max_colwidth', None)

# 4. Print the sample
print(sample_missing)

                             account_name  \
8829                     عميل مخزن الجمله
387                           صيدليه وائل
177                       اداره شريف شريف
7425                      ملاك نجيب مندوب
8606                            ايمن عبود
6201                        منه بكر صباحي
3516                 صيدليه نقدي الموظفين
3668               محمد بلال مندوب موظف 9
8330                            صلاح موظف
391        صيدليه رؤوف حدايق االاهرام 002
5480                  صيدليه وليد وحيد001
4722                      ياسر سمير محاسب
69                   صيدليه محمد نقدي 055
7157                     ايهاب عبد السلام
891                     ش اداره عمرو لبيب
6190         احمد عياد ابوالنمرس اي سبلاي
6244                        رضوان اخرفيصل
7159                   محمود محروس ابو عز
5689            صيدليه هاني سعيد الدقي002
5184  صيدليه ايوب مصر القديمه اي سبلاي001

                                          account_address
8829                                                  NaN
387                                                   NaN
177                                                   NaN
7425                                                  NaN
8606                                                  NaN
6201                                                  NaN
3516                                                  NaN
3668                                                  NaN
8330                                                  NaN
391              284ز شارع الثروه المعدنيه البوابه الاولي
5480                                               عابدين
4722                                                  NaN
69                                          استلام المخزن
7157                                                  NaN
891                                                   NaN
6190               شارع السوق بجوار قهوه المواردي شبرامنت
6244      اخر شارع ابوبكر درويش علي ناصيه الشارع موبينيلA
7159                                                  NaN
5689  5ش ابراهيم احمد متفرع من التحرير بجوار كشري التحرير
5184   9 شارع محمد الصغير خلف قسم مصر القديمه مصر القديمه

In [16]:
import pandas as pd
import re
import numpy as np

# Function to extract the code and clean the name
def extract_branch_code(name):
    name = str(name)
    
    # This Regex searches for any word at the end of the name (that contains digits)
    match = re.search(r'([^\s]*\d+[^\s]*)$', name)
    
    if match:
        code = match.group(1) # The code we found
        
        # Remove the code from the original name
        clean_name = name.replace(code, '').strip()
        
        # Additional cleaning: If the user wrote (Cash, Credit, Installment, Supply Collection) 
        # before the code, remove it as well to clean the name
        clean_name = re.sub(r'(خط|نقدي|اجل|تحصيل سبلاي)\s*$', '', clean_name).strip()
        
        return pd.Series([clean_name, code])
    
    # If no numbers are found at the end, return the original name and a Null code
    return pd.Series([name, np.nan])

# Apply the function to create two new columns (Cleaned name and Branch code)
df[['clean_account_name', 'branch_code']] = df['account_name'].apply(extract_branch_code)

# Display a sample of the result to verify
print(df[['account_name', 'clean_account_name', 'branch_code']].dropna(subset=['branch_code']).head(15))

                               account_name  \
0        صيدليه مها مديريه امن الجيزه ش 003
1                   صيدليه السعدني فيصل 002
2           صيدليه مني احمد امبابه نقدي 004
3                   صيدليه الشفاء بشتيل 004
4        صيدليه مها مديريه امن الجيزه ش 003
5           صيدليه ايمن محمد ارض اللواء 009
6            صيدليه الحرمين الوراق نقدي 004
7                 صيدليه تقي مصطفي فيصل 001
8               صيدليه النخبه فيصل نقدي 070
9        صيدليه محمود العزباوي الجلاتمه 007
10          صيدليه فاطمه الزهراء الوراق 004
11  صيدليه عبد الله محمد الجديده الوراق 004
12               صيدليه حنان موسي غطاطي 002
13                 صيدليه السقا بشتيل س 004
14               صيدليه نور الهدي الهرم 070

                     clean_account_name branch_code
0        صيدليه مها مديريه امن الجيزه ش         003
1                   صيدليه السعدني فيصل         002
2                صيدليه مني احمد امبابه         004
3                   صيدليه الشفاء بشتيل         004
4        صيدليه مها مديريه امن الجيزه ش         003
5           صيدليه ايمن محمد ارض اللواء         009
6                 صيدليه الحرمين الوراق         004
7                 صيدليه تقي مصطفي فيصل         001
8                    صيدليه النخبه فيصل         070
9        صيدليه محمود العزباوي الجلاتمه         007
10          صيدليه فاطمه الزهراء الوراق         004
11  صيدليه عبد الله محمد الجديده الوراق         004
12               صيدليه حنان موسي غطاطي         002
13                 صيدليه السقا بشتيل س         004
14               صيدليه نور الهدي الهرم         070

In [17]:
# Extract only the numbers from the branch code column and ignore any letters
df['branch_code'] = df['branch_code'].str.extract(r'(\d+)')

# Display a sample to ensure cleanliness
print(df[['account_name', 'branch_code']].dropna(subset=['branch_code']).head(10))

                         account_name branch_code
0  صيدليه مها مديريه امن الجيزه ش 003         003
1             صيدليه السعدني فيصل 002         002
2     صيدليه مني احمد امبابه نقدي 004         004
3             صيدليه الشفاء بشتيل 004         004
4  صيدليه مها مديريه امن الجيزه ش 003         003
5     صيدليه ايمن محمد ارض اللواء 009         009
6      صيدليه الحرمين الوراق نقدي 004         004
7           صيدليه تقي مصطفي فيصل 001         001
8         صيدليه النخبه فيصل نقدي 070         070
9  صيدليه محمود العزباوي الجلاتمه 007         007

In [18]:
df.head()

,id,supplier_id,invoice_id,prod_id,product_name,quantity,discount,total_amount,account_id,account_name,...,user_name,employee_name,city,region,area,area_id,creation_date,created_at,clean_account_name,branch_code
0,48652728,59,32259,7,سيبروسين مرهم س--ج,10,15.0,178.50,637,صيدليه مها مديريه امن الجيزه ش 003,...,نهى الدالى,نهى الدالى,الجيزة,القاهرة الكبرى,الجيزة,NaN,2025-05-25 13:43:10,2026-05-19 16:29:03,صيدليه مها مديريه امن الجيزه ش,003
1,48652935,59,32281,7,سيبروسين مرهم س--ج,3,15.0,53.55,4365,صيدليه السعدني فيصل 002,...,نهى الدالى,نهى الدالى,الجيزة,القاهرة الكبرى,فيصل,NaN,2025-05-25 14:35:04,2026-05-19 16:29:03,صيدليه السعدني فيصل,002
2,48653089,59,32301,7,سيبروسين مرهم س--ج,2,21.0,33.18,3297,صيدليه مني احمد امبابه نقدي 004,...,اسماء رجب,اسماء رجب,الجيزة,القاهرة الكبرى,إمبابة,NaN,2025-05-25 15:21:21,2026-05-19 16:29:03,صيدليه مني احمد امبابه,004
3,48653301,59,32334,7,سيبروسين مرهم س--ج,5,20.0,84.00,5734,صيدليه الشفاء بشتيل 004,...,اسماء رجب,اسماء رجب,الجيزة,القاهرة الكبرى,بشتيل,NaN,2025-05-25 20:49:54,2026-05-19 16:29:03,صيدليه الشفاء بشتيل,004
4,49140754,59,100804,7,سيبروسين مرهم س--ج,10,17.0,174.30,637,صيدليه مها مديريه امن الجيزه ش 003,...,نهى الدالى,نهى الدالى,الجيزة,القاهرة الكبرى,الجيزة,NaN,2026-04-12 13:51:32,2026-05-19 16:47:49,صيدليه مها مديريه امن الجيزه ش,003

In [19]:
# df.drop(columns=["account_code"], inplace=True)

In [18]:
# 1. Replace the old data with the cleaned data in the original column
df['account_name'] = df['clean_account_name']

# 2. Delete the temporary column (clean_account_name) as it is no longer needed
df.drop(columns=['clean_account_name'], inplace=True)

# Print the first 5 rows to verify the result and order
print(df[['account_name', 'branch_code']].head())

                     account_name branch_code
0  صيدليه مها مديريه امن الجيزه ش         003
1             صيدليه السعدني فيصل         002
2          صيدليه مني احمد امبابه         004
3             صيدليه الشفاء بشتيل         004
4  صيدليه مها مديريه امن الجيزه ش         003

In [21]:
df.head()

,id,supplier_id,invoice_id,prod_id,product_name,quantity,discount,total_amount,account_id,account_name,...,user_id,user_name,employee_name,city,region,area,area_id,creation_date,created_at,branch_code
0,48652728,59,32259,7,سيبروسين مرهم س--ج,10,15.0,178.50,637,صيدليه مها مديريه امن الجيزه ش,...,6,نهى الدالى,نهى الدالى,الجيزة,القاهرة الكبرى,الجيزة,NaN,2025-05-25 13:43:10,2026-05-19 16:29:03,003
1,48652935,59,32281,7,سيبروسين مرهم س--ج,3,15.0,53.55,4365,صيدليه السعدني فيصل,...,6,نهى الدالى,نهى الدالى,الجيزة,القاهرة الكبرى,فيصل,NaN,2025-05-25 14:35:04,2026-05-19 16:29:03,002
2,48653089,59,32301,7,سيبروسين مرهم س--ج,2,21.0,33.18,3297,صيدليه مني احمد امبابه,...,137,اسماء رجب,اسماء رجب,الجيزة,القاهرة الكبرى,إمبابة,NaN,2025-05-25 15:21:21,2026-05-19 16:29:03,004
3,48653301,59,32334,7,سيبروسين مرهم س--ج,5,20.0,84.00,5734,صيدليه الشفاء بشتيل,...,137,اسماء رجب,اسماء رجب,الجيزة,القاهرة الكبرى,بشتيل,NaN,2025-05-25 20:49:54,2026-05-19 16:29:03,004
4,49140754,59,100804,7,سيبروسين مرهم س--ج,10,17.0,174.30,637,صيدليه مها مديريه امن الجيزه ش,...,6,نهى الدالى,نهى الدالى,الجيزة,القاهرة الكبرى,الجيزة,NaN,2026-04-12 13:51:32,2026-05-19 16:47:49,003

In [19]:
# Total number of rows in the sheet
total_rows = len(df)

# Columns for which we want to check the fill rate
columns_to_check = ['area', 'city', 'region']

print("--- Data Fill Rate for each column ---")

for col in columns_to_check:
    # Calculate the number of non-Null rows
    filled_count = df[col].notna().sum()
    
    # Calculate the percentage
    percentage = (filled_count / total_rows) * 100
    
    # Print the result
    print(f"Column {col}: {filled_count} rows filled out of {total_rows} ({percentage:.2f}%)")

--- Data Fill Rate for each column ---
Column area: 7004 rows filled out of 10000 (70.04%)
Column city: 7004 rows filled out of 10000 (70.04%)
Column region: 7004 rows filled out of 10000 (70.04%)

In [23]:
# # استخدام encoding='utf-8-sig' يضمن توافق الحروف العربية مع Excel
# df.to_csv("updated3_file.csv", index=False, encoding='utf-8-sig')

In [20]:
# Calculate the percentage of Nulls for each column
null_report = (df.isnull().sum() / len(df) * 100).round(2).sort_values(ascending=False)

# Print the report as a table
print("--- Percentage of Missing Data (Nulls) in Columns ---")
print(null_report.astype(str) + ' %')

--- Percentage of Missing Data (Nulls) in Columns ---
area_id            100.0 %
branch_code        42.78 %
employee_name      32.79 %
city               29.96 %
region             29.96 %
area               29.96 %
account_address     25.6 %
user_name           5.12 %
product_name         0.0 %
id                   0.0 %
prod_id              0.0 %
invoice_id           0.0 %
supplier_id          0.0 %
user_id              0.0 %
account_name         0.0 %
total_amount         0.0 %
account_id           0.0 %
discount             0.0 %
quantity             0.0 %
creation_date        0.0 %
created_at           0.0 %
dtype: str

In [25]:
# # 1. إنشاء قاموس (Mapping) بيربط كل user_id بالاسم بتاعه من الصفوف المليانة
# # بنستخدم dropna عشان نضمن إننا بنأخد الأسماء المتاحة بس
# id_to_name = df.dropna(subset=['user_name']).set_index('user_id')['user_name'].to_dict()

# # 2. عمل Update للقيم الفاضية في user_name بناءً على الـ user_id
# # الكود ده بيقول: لو الـ user_name فاضي، روح للـ id بتاعه، وشوف الاسم المقابل ليه في القاموس
# df['user_name'] = df['user_name'].fillna(df['user_id'].map(id_to_name))

# # 3. التأكد من النتيجة
# print(f"عدد القيم الفاضية في user_name الآن: {df['user_name'].isna().sum()}")

In [21]:
# Calculate the percentage of Nulls for each column
null_report = (df.isnull().sum() / len(df) * 100).round(2).sort_values(ascending=False)

# Print the report as a table
print("--- Percentage of Missing Data (Nulls) in Columns ---")
print(null_report.astype(str) + ' %')

--- Percentage of Missing Data (Nulls) in Columns ---
area_id            100.0 %
branch_code        42.78 %
employee_name      32.79 %
city               29.96 %
region             29.96 %
area               29.96 %
account_address     25.6 %
user_name           5.12 %
product_name         0.0 %
id                   0.0 %
prod_id              0.0 %
invoice_id           0.0 %
supplier_id          0.0 %
user_id              0.0 %
account_name         0.0 %
total_amount         0.0 %
account_id           0.0 %
discount             0.0 %
quantity             0.0 %
creation_date        0.0 %
created_at           0.0 %
dtype: str

In [27]:
# # 1. إنشاء قاموس بيربط كل account_id بالعنوان بتاعه (من الصفوف اللي فيها عناوين)
# # بنستخدم dropna عشان نضمن إننا بنأخد العناوين المتاحة بس
# id_to_address = df.dropna(subset=['account_address']).set_index('account_id')['account_address'].to_dict()

# # 2. ملء القيم الفاضية في account_address بناءً على الـ account_id
# df['account_address'] = df['account_address'].fillna(df['account_id'].map(id_to_address))

# # 3. التأكد من النسبة الجديدة للـ Nulls
# new_null_rate = (df['account_address'].isnull().sum() / len(df) * 100).round(2)
# print(f"نسبة الفاضي الجديدة في account_address بقت: {new_null_rate} %")

In [28]:
# # 1. إنشاء قاموس الربط: أي user_id يقابله أي employee_name (من الصفوف المليانة)
# id_to_emp = df.dropna(subset=['employee_name']).set_index('user_id')['employee_name'].to_dict()

# # 2. ملء الفراغات في employee_name بناءً على الـ user_id
# df['employee_name'] = df['employee_name'].fillna(df['user_id'].map(id_to_emp))

# # 3. إضافي: لو لسه فيه فراغات، ممكن نساوي الـ employee_name بالـ user_name 
# # (لأن في الأغلب هما نفس الشخص)
# df['employee_name'] = df['employee_name'].fillna(df['user_name'])

# # 4. حساب النسبة بعد التنظيف
# new_null_rate = (df['employee_name'].isnull().sum() / len(df) * 100).round(2)
# print(f"نسبة الفاضي الجديدة في employee_name بقت: {new_null_rate} %")

In [22]:
# Calculate the percentage of Nulls for each column
null_report = (df.isnull().sum() / len(df) * 100).round(2).sort_values(ascending=False)

# Print the report as a table
print("--- Percentage of Missing Data (Nulls) in Columns ---")
print(null_report.astype(str) + ' %')

--- Percentage of Missing Data (Nulls) in Columns ---
area_id            100.0 %
branch_code        42.78 %
employee_name      32.79 %
city               29.96 %
region             29.96 %
area               29.96 %
account_address     25.6 %
user_name           5.12 %
product_name         0.0 %
id                   0.0 %
prod_id              0.0 %
invoice_id           0.0 %
supplier_id          0.0 %
user_id              0.0 %
account_name         0.0 %
total_amount         0.0 %
account_id           0.0 %
discount             0.0 %
quantity             0.0 %
creation_date        0.0 %
created_at           0.0 %
dtype: str

In [23]:
# 1. Fix user_name (grouped by supplier and user code)
df['user_name'] = df.groupby(['supplier_id', 'user_id'])['user_name'].transform(lambda x: x.bfill().ffill())

# 2. Fix employee_name (grouped by supplier and user code)
df['employee_name'] = df.groupby(['supplier_id', 'user_id'])['employee_name'].transform(lambda x: x.bfill().ffill())
df['employee_name'] = df['employee_name'].fillna(df['user_name'])

# 3. Fix account_address (grouped by supplier and account code)
df['account_address'] = df.groupby(['supplier_id', 'account_id'])['account_address'].transform(lambda x: x.bfill().ffill())

# Print results to verify
print("--- Remaining Nulls after fixing ---")
print(f"user_name nulls: {df['user_name'].isnull().sum()}")
print(f"employee_name nulls: {df['employee_name'].isnull().sum()}")
print(f"account_address nulls: {df['account_address'].isnull().sum()}")

--- Remaining Nulls after fixing ---
user_name nulls: 512
employee_name nulls: 0
account_address nulls: 2560

In [24]:
# Check which account names do not have a branch_code
not_a_branch = df[df['branch_code'].isna()]['account_name'].value_counts().head(20)

print("The most frequent names among the 45% that lack a code:")
print(not_a_branch)

The most frequent names among the 45% that lack a code:
account_name
صيدليه ياسر فتحي فيصل توصيل م س     984
حسام محمود                          620
صيدليه نقدي الموظفين                457
محمد محروس الجي                     220
طارق مصطفي                          166
محمد شوقي تحت التصريف               128
ش المصريه الدوائيه الجيزه            87
الحاج سيد عبداللطيف                  74
نقدي                                 68
ا حسام عبد اللطيف                    54
شهاب موظف                            45
الرحاب فيصل                          41
ايمن عبود                            30
موظفين المخزن                        28
صيدليه محمود مصطفي الجديده بولاق     25
عميل نقدي                            25
سهير رنان اخر فيصل                   23
فارم البترجي                         21
محمود وائل مندوب                     20
هاله الشيخ المنيب                    16
Name: count, dtype: int64

In [25]:
# 1. Create a unique dictionary for each area present in your area_mapping
unique_areas = sorted([area for area in area_mapping.values()])
# Link each area to a serial number starting from 1
clean_area_id_map = {area: i+1 for i, area in enumerate(unique_areas)}

# 2. Apply the dictionary to the 'area' column
df['area_id'] = df['area'].map(clean_area_id_map)

# 3. Verify the result (positive integers)
print(df[['area', 'area_id']].dropna().drop_duplicates().head(10))

          area  area_id
0       الجيزة     17.0
1         فيصل     99.0
2       إمبابة      9.0
3        بشتيل     69.0
5   أرض اللواء      5.0
6       الوراق     64.0
7      المنشية     56.0
9     الجلاتمة     16.0
12       غطاطي     95.0
14       الهرم     63.0

In [26]:
# Calculate the current percentage of Nulls for each column
null_report = (df.isnull().sum() / len(df) * 100).round(2).sort_values(ascending=False)

# Print the report as a table
print("--- Percentage of Missing Data (Nulls) in Columns ---")
print(null_report.astype(str) + ' %')

--- Percentage of Missing Data (Nulls) in Columns ---
branch_code        42.78 %
area               29.96 %
city               29.96 %
region             29.96 %
area_id            29.96 %
account_address     25.6 %
user_name           5.12 %
product_name         0.0 %
supplier_id          0.0 %
id                   0.0 %
prod_id              0.0 %
invoice_id           0.0 %
quantity             0.0 %
user_id              0.0 %
account_name         0.0 %
total_amount         0.0 %
account_id           0.0 %
discount             0.0 %
employee_name        0.0 %
creation_date        0.0 %
created_at           0.0 %
dtype: str

In [34]:
# # استخدام encoding='utf-8-sig' يضمن توافق الحروف العربية مع Excel
# df.to_csv("updated5_file.csv", index=False, encoding='utf-8-sig')

In [27]:
import re

# 1. Text cleaning function using standard Python (to bypass PyArrow compatibility issues)
def clean_product_name(text):
    if pd.isna(text):
        return text
    # Remove any strange symbols, keeping Arabic characters, English letters, numbers, and spaces
    cleaned_text = re.sub(r'[^\sa-zA-Z0-9\u0600-\u06FF]', ' ', str(text))
    # Standardize double spaces and trim outer spaces
    return re.sub(r'\s+', ' ', cleaned_text).strip()

# 2. Safely apply the cleaning function to the column
df['product_name'] = df['product_name'].apply(clean_product_name)

# 3. Intelligent function to select the "most frequent name" (Mode) for each product
def get_most_frequent_name(series):
    mode_values = series.mode()
    # Choose the name that appears most often; if none, choose the first encountered
    return mode_values[0] if not mode_values.empty else series.iloc[0]

# 4. Apply unification based on supplier and product ID
df['product_name'] = df.groupby(['supplier_id', 'prod_id'])['product_name'].transform(get_most_frequent_name)

# 5. Display a sample of the cleaned data for review
print(df[['supplier_id', 'prod_id', 'product_name']].drop_duplicates().sample(30))

      supplier_id  prod_id                        product_name
7002           75    18036            بلوكاتنس 10 160مجم 28قرص
156            59       16                          نيوبول نقط
8611           76      251                اوكسيمت كبار نقط س ج
4397           69    17539                    بروكورالان 5 مجم
8151           76    18273                      فاى سينس صابون
8430           76     4095                تلفاست 120 2شريط س ج
7309           75    24325    بانادول ادفانس 500مجم علبه كبيرة
5454           72   712535                         فلافيسيف30ش
9973           80    14923                اليكويس 5 ق سعر جديد
3200           67     9939                 سويتال اقراص 100قرص
9231           80    12740  فيلداجلوز 50 1000 بلس30قرص انسبيرا
9996           80      212              سيبتازول شراب اسكندريه
4664           69     2712           ليمتلس بى كومبلكس 30 فيلم
8348           76    10121              استيروماب 20مجم 30 قرص
1342           60    12938         نيفيلوب 5مج 21ق س ج ماركيرل
4903           69    15407                   برين اوكس 20كبسول
8803           76    17833                ايزوروميدرم جيل 30جم
7233           75     4999                ليبراكس 30قرص س جديد
2145           63    21740       ابيكساتراك 5مجم30قرص س ج ايفا
4472           69    23993                 فوناسبير10مجم اقراص
2126           63    13728              سباركل شامبو600مل بمبى
8165           76    17035                  اماريل 3مجم 3شرائط
3576           67     5700         مالتى ريلاكس 5مجم 20قرص س ج
9931           80    14121                    بلينك قطرة ثلاجة
5968           72   709984                       ميكسيدرم صغير
7724           75    25046                  تادالونج20ج س جديد
5914           72   710260                       نيفيكسال فورت
1484           60     9367                 ميرتى 30ك الفرعونية
8591           76     1079               تريتاس 1 25 اقراص س ج
5562           72   105036                          جنجر 30قرص

In [36]:
# # استخدام encoding='utf-8-sig' يضمن توافق الحروف العربية مع Excel
# df.to_csv("updated11_file.csv", index=False, encoding='utf-8-sig')

In [28]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import networkx as nx

print("🚀 Starting Entity Resolution process...")

# 1. Extract unique entities (to avoid unnecessary calculations on 10,000 rows)
# We take supplier, account code, name, address, and area
entities = df[['supplier_id', 'account_id', 'account_name', 'account_address', 'area']].drop_duplicates().reset_index(drop=True)

# 2. Prepare text for matching (merging name with address to increase matching accuracy)
entities['match_text'] = entities['account_name'].fillna('') + ' ' + entities['account_address'].fillna('')
# Standardize empty areas into one block to compare them with each other
entities['area_block'] = entities['area'].fillna('UNKNOWN')

# 3. Prepare TF-IDF (using the magical 'char_wb' to handle Arabic spelling errors)
# This splits words into characters (e.g., "شفا" and "شفاء" will appear very similar)
vectorizer = TfidfVectorizer(analyzer='char_wb', ngram_range=(2, 4))

# 4. Prepare a Graph network to link matched pharmacies
G = nx.Graph()
for idx in entities.index:
    G.add_node(idx) # Each unique pharmacy is a "node" in the network

# Required similarity ratio to merge two pharmacies (85% is an excellent, tested ratio)
SIMILARITY_THRESHOLD = 0.85 

# 5. Matching within each region (Blocking) to save processing time
blocks = entities['area_block'].unique()
for block in blocks:
    # Identify row indices for the current region
    block_indices = entities[entities['area_block'] == block].index
    if len(block_indices) < 2:
        continue # If the region has less than one pharmacy, skip it
    
    # Convert texts to numbers and calculate similarity ratio
    block_texts = entities.loc[block_indices, 'match_text']
    tfidf_matrix = vectorizer.fit_transform(block_texts)
    sim_matrix = cosine_similarity(tfidf_matrix)
    
    # Extract matches that passed the Threshold
    for i in range(len(block_indices)):
        for j in range(i + 1, len(block_indices)):
            if sim_matrix[i, j] >= SIMILARITY_THRESHOLD:
                # If they are similar, draw an "edge" between them in the network
                G.add_edge(block_indices[i], block_indices[j])

# 6. Extract unified entities (Connected Components)
# This function gathers all pharmacies linked together and assigns them a single global code
components = list(nx.connected_components(G))

global_mapping = {}
for global_id, component in enumerate(components, start=1):
    # Create a unified code (Example: GLB_0001)
    new_global_code = f"GLB_{global_id:04d}"
    for node_idx in component:
        global_mapping[node_idx] = new_global_code

# 7. Add the unified code to the entities table
entities['Global_Account_ID'] = entities.index.map(global_mapping)

# 8. Merge the unified code into your original table
df = df.merge(
    entities[['supplier_id', 'account_id', 'Global_Account_ID']], 
    on=['supplier_id', 'account_id'], 
    how='left'
)

# --- Success Statistics ---
original_count = len(entities)
unified_count = entities['Global_Account_ID'].nunique()
print(f"✅ Matching completed successfully!")
print(f"📊 Number of entities before merging (with duplication across suppliers): {original_count}")
print(f"🎯 Actual number of entities (Global IDs): {unified_count}")
print(f"🔥 Detected and merged {original_count - unified_count} duplicate entities across suppliers.")

🚀 Starting Entity Resolution process...
✅ Matching completed successfully!
📊 Number of entities before merging (with duplication across suppliers): 1104
🎯 Actual number of entities (Global IDs): 1092
🔥 Detected and merged 12 duplicate entities across suppliers.

In [29]:
# 1. Extract the unified codes that contain more than one entity (i.e., those that were merged)
merged_global_ids = entities['Global_Account_ID'].value_counts()
merged_global_ids = merged_global_ids[merged_global_ids > 1].index

print("🔍 Sample of pharmacies that the algorithm identified as a single entity and merged:\n")

# 2. Display the first 5 merged cases as an example for review
for gid in merged_global_ids[:5]:
    group = entities[entities['Global_Account_ID'] == gid]
    
    print(f"🔹 Unified Entity (Global ID): {gid} 📍 Area: {group['area'].iloc[0]}")
    
    for _, row in group.iterrows():
        # Display the supplier, local code, name, and address for each version
        print(f" 🔻 Supplier ({row['supplier_id']}) - Local Code ({row['account_id']}): {row['account_name']}")
        print(f"      Address: {row['account_address']}")
        
    print("-" * 60)

🔍 Sample of pharmacies that the algorithm identified as a single entity and merged:

🔹 Unified Entity (Global ID): GLB_0017 📍 Area: الهرم
 🔻 Supplier (59) - Local Code (6797): صيدليه المروه الهرم
      Address: شارع الهرم عماره بيتزا كينج
 🔻 Supplier (76) - Local Code (5103): صيدليه المروه ش الهرم
      Address: 360 شارع الهرم عماره بيتزا كينج
------------------------------------------------------------
🔹 Unified Entity (Global ID): GLB_0075 📍 Area: كرداسة
 🔻 Supplier (59) - Local Code (5150): صيدليه اسلام ابو
      Address: كرداسه شارع البنك بجوار مسجد الشاعر
 🔻 Supplier (72) - Local Code (3939): صيدليه اسلام ابو السعود كرداسه
      Address: كرداسه شارع البنك بجوار مسجد الشاعر
------------------------------------------------------------
🔹 Unified Entity (Global ID): GLB_0088 📍 Area: أرض اللواء
 🔻 Supplier (59) - Local Code (5197): صيدليه خلود الحديثه ارض اللواء
      Address: 12ش مسجد الحسن امام فيلا عبد الوهاب ارض اللواء
 🔻 Supplier (69) - Local Code (5763): صيدليه خلود الحديثه استلام ارض اللواء
      Address: 12ش مسجد الحسن امام فيلا علي عبد الوهاب ارض اللواء
------------------------------------------------------------
🔹 Unified Entity (Global ID): GLB_0113 📍 Area: فيصل
 🔻 Supplier (59) - Local Code (4776): صيدليه محمود سيد المطبعه فيصل
      Address: شارع عبدالمقصود شلتوت ناصيه ماركت بيم المطبعه فيصل
 🔻 Supplier (67) - Local Code (6342): صيدليه محمود سيد
      Address: شارع عبدالمقصود شلتوت ناصيه ماركت بيم المطبعه فيصل
------------------------------------------------------------
🔹 Unified Entity (Global ID): GLB_0153 📍 Area: الجيزة
 🔻 Supplier (59) - Local Code (4602): صيدليه احمد حلمي الجيزه
      Address: 22 ا شارع مراد ميدان الجيزه امام كنيسه المطرانيه
 🔻 Supplier (59) - Local Code (6310): صيدليه احمد حلمي الجيزه
      Address: 2ا شارع مراد ميدان الجيزه امام كنيسه المطرانيه
------------------------------------------------------------

In [39]:
# # 1. توحيد اسم الصيدلية ليكون متطابقاً في كل الموردين لنفس الكيان (Global ID)
# df['account_name'] = df.groupby('Global_Account_ID')['account_name'].transform('first')

# # 2. توحيد العنوان ليكون متطابقاً في كل الموردين لنفس الكيان (Global ID)
# df['account_address'] = df.groupby('Global_Account_ID')['account_address'].transform('first')

# print("✅ تم توحيد نصوص الأسماء والعناوين بنجاح بناءً على الـ Global ID!")

In [30]:
# 1. Intelligent function to choose the "most frequent value" (Mode)
def get_most_frequent_value(series):
    mode_values = series.mode()
    return mode_values[0] if not mode_values.empty else series.iloc[0]

# 2. Unify the pharmacy name based on the most frequent name for each Global ID
df['account_name'] = df.groupby('Global_Account_ID')['account_name'].transform(get_most_frequent_value)

# 3. Unify the address based on the most frequent address for each Global ID
df['account_address'] = df.groupby('Global_Account_ID')['account_address'].transform(get_most_frequent_value)

print("🎯 Names and addresses have been successfully unified globally based on the most frequent value (Mode)!")

🎯 Names and addresses have been successfully unified globally based on the most frequent value (Mode)!

In [ ]:
df.to_csv("updated16_file.csv", index=False, encoding='utf-8-sig')